### ISSUE TITLE
Power from Linky A Slot

### ISSUE THREAD

**Issue by xav-git** [hallard/Denky-D4#4]
Hello, 
I did not find any information whether this module could be plugged directly on Linky  "A" pin in order to benefit from the power supply provided by linky power meters. 

I assume that an independant power source would be needed to power this module, am I right ?
Regards.

**Comment by hallard** [comment]
Hi, 
you're correct, Denky D4 needs a power supply because Tasmota is running all time (real time reading/sending data).

Powered by A pin is not possible with Denky D4 because it's not it's main function but also because hardware is not designed for. Even if it was designed for, working mode would be different, sleeping until we have enough power, then connect to wifi send data and go to sleep again.
We're working on Winky version this one would be powered with A pin
https://miniprojets.net/index.php/2022/02/04/winky-version-2-open-source-projet-pour-linky-avec-wifi/

**Comment by xav-git** [comment]
Thanks for quick anwser. I understand the power constraints
